[tool.poetry]
name = "csv-to-google-form"
version = "0.1.0"
description = "A script to parse CSV files and post data to a Google Form"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.3"
requests = "^2.26.0"
loguru = "^0.5.3"
flake8 = "7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
